title: Sandorex's Cheatsheets
description: Cheatsheets for variety of things
url: https://sandorex.github.io
baseurl: /cheatsheets

theme: jekyll-theme-primer
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-github-metadata
relative_links:
  enabled: true
  collections: true
markdown: GFM

include:
  - README.md
  - LICENSE
