title: Sandorex's Cheatsheets
description: Cheatsheets for variety of things

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
markdown: GFM
