baseURL = "https://sandorex.github.io/notes-and-cheatsheets"
title = "Notes & Cheatsheets"
theme = "hugo-notepadium"
copyright = "© 2020 by Aleksandar Radivojević"
languageCode = "en-us"
enableRobotsTXT = true

# required when baseURL is a subURL (aka /something after the url)
RelativeURLs = true
CanonifyURLs = true

# remove /post from url
[permalinks]
post = "/:slug"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"
dateFormat = "January 2, 2006"
license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/></a>This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>CC BY 4.0 License</a>.<br>All code is licensed under the <a href=/LICENSE-MIT>MIT License</a>"

[params.math]
enable = true
use = "katex"

[params.syntax]
use = "none"
theme = "dracula"

[params.nav]
showCategories = false
showTags = true

[[params.nav.custom]]
title = "About"
url = "/about"
